server:
  servlet:
    context-path: /supershop

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/geekbrains?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789

  thymeleaf:
    cache: false